// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package tests

type Config struct {
	App struct {
		Name string `json:"name"`

		Port int64 `json:"port"`
	} `json:"app"`

	Token Secret `json:"token,omitempty"`

	Output string `json:"output,omitempty"`
}
