// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package main

type Config struct {
	Name string `json:"name"`

	Private struct {
		EnvValue Secret `json:"env_value"`

		ConfiguredValue Secret `json:"configured_value"`
	} `json:"private"`

	Public struct {
		EnvValue string `json:"env_value"`

		DataPath string `json:"data_path"`
	} `json:"public"`
}
