// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package main

type Config struct {
	RedMarker RedMarkerSecret `json:"red_marker"`

	Partial PartialSecret `json:"partial"`

	Fingerprint FingerprintSecret `json:"fingerprint"`
}
