// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package main

type Config struct {
	Server Server `json:"server"`
}

type Server struct {
	Host string `json:"host"`

	Port int64 `json:"port"`
}
