// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package main

type Config struct {
	App struct {
		Name string `json:"name"`
	} `json:"app"`

	PrivateValues struct {
		FromEnv Secret `json:"from_env"`
	} `json:"private_values"`

	PublicValues struct {
		FromEnv string `json:"from_env"`

		ConfigPath string `json:"config_path"`

		DataPath string `json:"data_path"`

		OptionalValue string `json:"optional_value"`
	} `json:"public_values"`
}
